#pragma once

// @generated by aten/src/ATen/gen.py

#include "ATen/LegacyTHDispatcher.h"

namespace at {

struct LegacyTHCPUQInt32Dispatcher final : public LegacyTHDispatcher {
  explicit LegacyTHCPUQInt32Dispatcher();

};

} // namespace at
