#pragma once

// @generated by aten/src/ATen/gen.py

#include "ATen/LegacyTHDispatcher.h"

namespace at {

struct LegacyTHQuantizedCPUQUInt8Dispatcher final : public LegacyTHDispatcher {
  explicit LegacyTHQuantizedCPUQUInt8Dispatcher();

};

} // namespace at
