#pragma once

// @generated by aten/src/ATen/gen.py

#include "ATen/LegacyTHDispatcher.h"

namespace at {

struct LegacyTHCUDAQUInt8Dispatcher final : public LegacyTHDispatcher {
  explicit LegacyTHCUDAQUInt8Dispatcher();

};

} // namespace at
