#pragma once

// @generated by aten/src/ATen/gen.py

#include "ATen/LegacyTHDispatcher.h"

namespace at {

struct LegacyTHQuantizedCPUQInt32Dispatcher final : public LegacyTHDispatcher {
  explicit LegacyTHQuantizedCPUQInt32Dispatcher();

};

} // namespace at
