#pragma once

// @generated by aten/src/ATen/gen.py

#include "ATen/LegacyTHDispatcher.h"

namespace at {

struct LegacyTHCPUQUInt8Dispatcher final : public LegacyTHDispatcher {
  explicit LegacyTHCPUQUInt8Dispatcher();

};

} // namespace at
