#pragma once

// @generated by aten/src/ATen/gen.py

#include "ATen/LegacyTHDispatcher.h"

namespace at {

struct LegacyTHCUDAQInt32Dispatcher final : public LegacyTHDispatcher {
  explicit LegacyTHCUDAQInt32Dispatcher();

};

} // namespace at
